Apollo:
  Host: "http://localhost:18080"
  AppID: "go-brick-example"
  Cluster: "dev"
  Namespace: "application"
  IsBackup: true
  Secret: "7635dbdc38c348079b7ad71cc6c2444c"
  Label: ""
  SyncTimeout: 5